### ISSUE TITLE
牛逼啊,直接干这么高让我们无路可走

### ISSUE THREAD

**Issue by ily666666** [juhongm999/hsnet#1]
牛逼啊,直接干这么高让我们无路可走

**Comment by zbf1991** [comment]
Seems that they use 400*400 size during influence rather than original image size

**Comment by ily666666** [comment]
所以,你认为如果把尺寸改为224效果会降低吗

**Comment by ily666666** [comment]
> Seems that they use 400*400 size during influence rather than original image size

所以,你认为如果把尺寸改为224效果会降低吗

**Comment by zbf1991** [comment]
see the performance of PFENet on COCO, a fixed size generates a higher performance than the original size.

**Comment by ily666666** [comment]
对于FSS数据集,他们本来就有一个固定的尺寸224*224,变换到400*400 影响应该不大.
另外,我刚刚又看了一下PFENet的论文,这篇论文(HSNet)表格中PFENet的数据也是固定尺寸473*473得到的.
不知道别的什么情况,但是有一定的提升这一点是毋庸置疑的.

**Comment by juhongm999** [comment]
@ily666666 @zbf1991 

During both training and evaluation, we use fixed image size of 400 x 400 following recent state of the arts. For example, PPNet and RePRI both use spatial size of 417 x 417 for the input images. PFENet uses both fixed (473 x 473) and original image sizes in its evaluation. In our experiments, we found that larger image sizes typically  (> 417) result in better mIoU results but we use image size of 400 x 400 as the image sizes of 417x417 and 473x473 seemed random numbers to us and using size of 400 x 400 already surpasses previous state of the arts. To see the primary source of performance improvements, please refer ablation study in Section 5.2 of our paper.

**Comment by tymatfd** [comment]
> 牛逼啊,直接干这么高让 

> 牛逼啊,直接干这么高让我们无路可走

握手，看到这结果当时心都凉了。现在还好已经有至少两个工作比他还要高了，我可以彻底躺平了
