### ISSUE TITLE
Experiment without support feature masking

### ISSUE THREAD

**Issue by AyanamiReiFan** [juhongm999/hsnet#11]
How to do the experiment without support feature masking？Should I retrain whole model without support feature masking？

I simply delete the 52th line in hsnet.py during inference(use the checkpoint you given):
`support_feats = self.mask_feature(support_feats, support_mask.clone())`

and got a poor result:
```
fold0
*** Test [@Epoch 00] Avg L: 0.00000  mIoU: 27.50   FB-IoU: 51.22   ***
fold1
*** Test [@Epoch 00] Avg L: 0.00000  mIoU: 41.96   FB-IoU: 58.30   ***
fold2
*** Test [@Epoch 00] Avg L: 0.00000  mIoU: 33.78   FB-IoU: 48.98   ***
fold3
*** Test [@Epoch 00] Avg L: 0.00000  mIoU: 32.07   FB-IoU: 51.38   ***
```

**Comment by juhongm999** [comment]
Did you evaluate the provided models that are trained without support feature masking [[link](https://drive.google.com/drive/folders/14JAwx1TCohj2_ZiMFeDcTB9HBINxmir2)]?

**Comment by AyanamiReiFan** [comment]
Thanks，the result is right with this checkpoint
