### ISSUE TITLE
about coco2pascal

### ISSUE THREAD

**Issue by asdnjadsn** [juhongm999/hsnet#14]
that is a great job, and very help to me. but How to verify the coco model on pascal in code？ please

**Comment by juhongm999** [comment]
COCO->PASCAL evaluation is performed using [COCO-trained models](https://drive.google.com/drive/folders/1WpwmCQzxTWhJD5aLQhsgJASaoxxqmFUk).
We simply excluded common object classes on each fold in PASCAL-5i following the work of [RePRI](https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation).

**Comment by moonsh** [comment]
@juhongm999 [RePRI](https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation).   I found something strange. In the 
 RePRI paper, the mean accuracy for one shot (CocoToPascal) is 34.0 but in your paper, it's 63.2.   The same approach but different accuracy. What's the difference?
