### ISSUE TITLE
VOC dataset mismatching

### ISSUE THREAD

**Issue by songyinan1** [juhongm999/hsnet#17]
hi, I have noticed that there is a gap between your folds' txt files and the folder "SegmentationClassAug". 
The total number of masks in "SegmentationClassAug" is 12031, while after removing duplicate files on the folds' TXT statistics of trn and val folder, the total number of image list is only 11473, could you please tell me why don't the numbers match up? Or am I missing some data-processing detail?

**Comment by juhongm999** [comment]
We used the image/mask list for each fold from previous work, e.g., [PMM repo](https://github.com/Yang-Bob/PMMs/tree/master/data_list) for fairness in using training/validation data. I'm not sure where the lists are originally from so I suggest you to contact authors of either the original work (OSLSM) or PMM.

**Comment by songyinan1** [comment]
> We used the image/mask list for each fold from previous work, e.g., [PMM repo](https://github.com/Yang-Bob/PMMs/tree/master/data_list) for fairness in using training/validation data. I'm not sure where the lists are originally from so I suggest you to contact authors of either the original work (OSLSM) or PMM.

Thanks, I will go to check the previous work.
