### ISSUE TITLE
Question . 5 shot results

### ISSUE THREAD

**Issue by moonsh** [juhongm999/hsnet#18]
Hi, first, thank you for sharing your great work !.

I just wonder how you got the 5-shot results for tables 1,2 and 3 in the paper.

Did you train on 1 shot and used this model for getting 5-shot  or did you train again using 5-shot ?

and the figure A4 in the paper is from resnet101 backbone?  

Thank you.

**Comment by juhongm999** [comment]
Did you train on 1 shot and used this model for getting 5-shot or did you train again using 5-shot ?

- Yes. We train our model in 1-shot setting and show that the trained model can be used for n-shot setting without loss of generality in Section 4.5 of our paper.

and the figure A4 in the paper is from resnet101 backbone?

- Yes. All the qualitative results in the paper (including supp.) are produced by model with resnet101 backbone.

**Comment by moonsh** [comment]
Thank you very much.
