### ISSUE TITLE
about effect

### ISSUE THREAD

**Issue by ily666666** [juhongm999/hsnet#2]
I download your code,and train it according to the readme.txt, but when I train it 150 epoches,Its mIOU up to 82.47%.So ,can you tell me how should I train to achieve the effect of the essay.

**Comment by ily666666** [comment]
backbone is resnet50

**Comment by ily666666** [comment]
python train.py --backbone resnet50 --benchmark fss --lr 1e-3 --bsz 10
And this is one info in log.txt
*** Validation [@Epoch 138] Avg L: 0.12781  mIoU: 82.47   FB-IoU: 89.57   ***

**Comment by ily666666** [comment]
Sorry ,I don't mean anything else, I am just puzzled

**Comment by juhongm999** [comment]
Training HSNet on FSS-1000 dataset takes approximately 3 days until convergence (when trained with four 2080 Ti GPUs).
If you are training with one GPU only, it will take longer.
As you see in our tensorboard log we provided in the README.md (https://drive.google.com/file/d/1i9WlwCEqK4XOdBRh0nShtxxEdWe-1q_r/view), the best model is retrieved when the validation mIoU is the highest (82.85) at epoch 731 (as seen below).
<img width="644" alt="스크린샷 2021-04-13 오후 3 09 18" src="https://user-images.githubusercontent.com/41140817/114504789-5f0bb000-9c6a-11eb-803d-cc4ca7a32d95.png">

Also FSS-1000 consists of training/validation/**test** splits. The model (having val mIoU of 82.85) should be further tested using command below:

python **test**.py --backbone resnet50 --benchmark fss --nshot 1 --load "path_to_trained_model/best_model.pt"

which gives 1-shot results of 85.5 (mIoU) on the test split of FSS-1000 as in our paper.
If you have any further issues, please leave us a comment.
