### ISSUE TITLE
Paper Result

### ISSUE THREAD

**Issue by Ehteshamciitwah** [juhongm999/hsnet#21]
Hello,

I am training your model resnet50 on pascal (0 fold). After 70 epochs, the max MIou is 62.89. Now the MIou is Fluctuating below the maximum value. Can you suggest how I can achieve the paper results? are there any special parameters to achieve paper results?

Thank you

**Comment by juhongm999** [comment]
To reproduce the results, you have to train the model at least 350 epochs.

**Comment by Ehteshamciitwah** [comment]
Thank you. I will train until 350 epochs and let you know.

**Comment by Ehteshamciitwah** [comment]
At epoch 128, it raise an error as mentioned below. furthermore, I achieve 63.94 Miou for pascal 1shot, 0 fold on res50. 

![image](https://user-images.githubusercontent.com/79190474/160955175-938dbd70-d4ee-4692-a6a7-23d2ab0ea5a2.png)

**Comment by juhongm999** [comment]
What pytorch & torchvision version do you have?

**Comment by Ehteshamciitwah** [comment]
Hello,
After uploading my previous best model, I again start training and achieve paper results on resnet50 fold 0. However, I have these version
Python =3.6.13
PyTorch =1.10.0
torchvision=0.11.1

Thank you for your wonderful work. I am just curious about one thing.  Why the MIou of the first batch is always low during validations. 

![image](https://user-images.githubusercontent.com/79190474/161176125-52a02906-ec7b-411e-aa1b-e32fd9a3fd0b.png)

**Comment by juhongm999** [comment]
At the beginning of each epoch, mIoU is always low because the mIoU is the average over all classses and IoU results of some classes are not computed (meaning its 0 IoU) in the beginning.

**Comment by Ehteshamciitwah** [comment]
Got it. Thank you very much
