### ISSUE TITLE
backbone feature

### ISSUE THREAD

**Issue by Catofblue** [juhongm999/hsnet#27]
thanks you nice work !
I have a question,  you use the backbone of resnet 50 and resnet101 to extract feature, why use  4 to 16 layers features

#res50   feat_ids = list(range(4, 17))
        if hid + 1 in feat_ids: 
            feats.append(feat.clone())

        feat = backbone.__getattr__('layer%d' % lid)[bid].relu.forward(feat)

    return feats

**Comment by juhongm999** [comment]
We use feature layers of stages 2, 3, and 4 of ResNet which correspond to those layer indices.
