### ISSUE TITLE
Unfair Comparisons especially on COCO

### ISSUE THREAD

**Issue by deepAICrazy** [juhongm999/hsnet#6]
https://github.com/juhongm999/hsnet/issues/5

This is not the case actually because you did not fairly compare your results with REPRI and PFENet in the table1 where the results are directly copied from their papers. In https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/master/src/dataset/transform.py#L80 they keep the aspect ratio of the resized images to be the same as the original image, but in your implementation https://github.com/juhongm999/hsnet/blob/e288916debe5290b3e9554fb61e13a474e00f885/data/dataset.py#L25 the images are simply resized to be the aspect ratio 1:1 without keeping the original label.

For my second question, now that all previous methods use 417, 473 or the original sizes for evaluating COCO and PASCAL. 
I do not understand why did you use size 400 on COCO and PASCAL to create a brand **\*\*new\*\*** setting and make other people hard to follow to have a fair comparison, even if the size 400 does not bring the best performance according to your words. Normally we should show the setting of the best results. 
This is true the performance on Pascal will be slightly higher when the training size grows but they are still comparable. 
And the models of REPRI and PASCAL cannot be directly tested with 1:1 aspect ratio because they are not trained with the images the 1:1 ratios in the non-255 regions.
However on COCO I have tested on PFENet. the results will be much lower when it is evaluated with the original labels without resize. it is the same to the results shownin PFENet it is also mentioned by https://github.com/juhongm999/hsnet/issues/1#issuecomment-816485819.
So I think it is unfair if you cannot show the COCO results with the original aspects and the original sizes (or 417, 473) to compare with related methods (REPRI, PFENET AND ASGNet and so on) because a smaller size for resizing labels does bring much better performance on COCO.

**Comment by deepAICrazy** [comment]
It is not all readers' duty for varifying your code if your paper is under review because a totally contradictory finding has been shown in other papers and comments. It will be better if you can show the results of COCO and PASCAL evaluated with the original aspect ratios and more recently used sizes like 473 and the original sizes before editing and closing my issue.

**Comment by juhongm999** [comment]
Thanks for the detailed feedback. We carefully read your comments, thus will get back to you with results you requested as soon as possible.

**Comment by juhongm999** [comment]
We've added & updated our comments.
Do they address your concerns?
