### ISSUE TITLE
Possible code simplification?

### ISSUE THREAD

**Issue by Parskatt** [juhongm999/hsnet#9]
Hi,

Here: 
https://github.com/juhongm999/hsnet/blob/2cd06324ef733004a4d0ef6ab594d16fd9d3061f/model/base/conv4d.py#L23-L34

Is a rather complicated function, which (if I understand it correctly) just strides the final two dimensions.
Could you instead simply do:

```python
out1 = x[...,::2,::2]
```

Perhaps there is something I'm missing here? Otherwise, I think it would make the code more readable.

**Comment by juhongm999** [comment]
Applying strides on the final two dimensions will indeed simplify the code having the same results as our code.
The reason why we wrote rather complicated functions is that in our experiments, torch.index_select() function performs much faster forward/backward passes (I guess it was the backward pass that gains dramatic speed gain: 2~3 times faster) than numpy style indexing as suggested.

**Comment by Parskatt** [comment]
Ah, that's super interesting!
Perhaps this should be discussed with the authors of pytorch?

**Comment by juhongm999** [comment]
Yup. Here I provide related issues:
https://github.com/pytorch/pytorch/issues/14231
https://github.com/pytorch/pytorch/issues/15245
https://github.com/pytorch/pytorch/pull/13420

**Comment by Parskatt** [comment]
Ah, good to hear that they seem to have fixed the performance. 
I'm using similar striding in my own project so I'm happy I don't have to complicate my code.

I'll close the issue.
